blueprint:
  name: DroidPad MQTT
  description: Execute an action when receive a DroidPad command
  domain: automation
  #source_url:
  #author: 
  input:
    mqtt_topic:
      name: MQTT Topic where received msgs are
      description: MQTT Topic where received msgs are
      selector:
        text:
          autocomplete: "DroidPad/Events"
          type: text

    event_type:
      name: Event Type
      description: >
        Please select what state you would like for your trigger.
      default: button
      selector:
        select:
          custom_value: true
          mode: dropdown
          options:
            - label: 1 - Switch
              value: "switch"
            - label: 2 - Slider
              value: "slider"
            - label: 3 - Joystick
              value: "joystick"
            - label: 4 - Button
              value: "button"
            - label: 5 - DPad
              value: "dpad"
                
mode: restart
max_exceeded: silent

triggers:
  trigger: mqtt
  topic: !input mqtt_topic

variables:
  event_type: !input event_type

action:
  - service: persistent_notification.create
    data_template:
      message: >
        {% set message = trigger.event.data %}
        {% if True %}
         Event Type: {{ event_type }}
        {% else %}
         Event Type: {{ event_type }}
        {% endif %}