blueprint:
  name: DroidPad MQTT
  description: Execute an action when receive a DroidPad command
  domain: automation
  #source_url:
  #author: 
  input:
    mqtt_topic:
      name: MQTT Topic where received msgs are
      description: MQTT Topic where received msgs are
      selector:
        text:
          autocomplete: "DroidPad/Events"
          type: text

    start_trigger_settings:
      name: "Start Trigger"
      icon: mdi:cog-outline
      collapsed: true
      input:
        event_type:
          name: Start Trigger - State
          description: >
            Please select what state you would like for your trigger.
            You can choose from ten options available in the dropdown menu.
            If your option is not in the dropdown menu then just type the state you would like to use in and click the save button.
            
            
            1 - Button Or Any State
            
            2 - ON
            
            3 - OFF
            4 - Unavailable
            5 - Unknown
            6 - Home
            7 - Not Home
            8 - Numeric State - Above
            9 - Numeric State - Below
            10 - Numeric State - Above & Below
            
            
            A numbering system has been implemented to facilitate navigation within the dropdown selections. Each number corresponds to a specific configuration,
            aiding users in identifying and adjusting the settings used within each selection. For instance, when selecting **8 - Numeric State - Above**
            as a dropdown option, settings marked **Used in options 8, 9 or 10** are required for that respective selection because number 8 is included in those options.
          default: button_any_state
          selector:
            select:
              custom_value: true
              mode: dropdown
              options:
                - label: 1 - Button Or Any State
                  value: "button_any_state"
                - label: 2 - ON
                  value: "on"
                - label: 3 - OFF
                  value: "off"
                - label: 4 - Unavailable
                  value: "unavailable"
                - label: 5 - Unknown
                  value: "unknown"
                - label: 6 - Home
                  value: "home"
                - label: 7 - Not Home
                  value: "not_home"
                - label: 8 - Numeric State - Above
                  value: "numeric_state_above"
                - label: 9 - Numeric State - Below
                  value: "numeric_state_below"
                - label: 10 - Numeric State - Above & Below
                  value: "numeric_state_above_below"

mode: restart
max_exceeded: silent

triggers:
  trigger: mqtt
  topic: !input mqtt_topic

variables:
  event_type: !input event_type

actions:
  - action: persistent_notification.create
    data:
    title: >
      DroidPad Event is {{ event_type }}
    message: "Value is {{ event_type }}"
      
      

