blueprint:
  name: DroidPad MQTT
  description: Execute an action when receive a DroidPad command
  domain: automation
  #source_url:
  #author: 
  min_version: 2022.4.0
  input:
    - mqtt_topic:
        name: MQTT Topic where received msgs are
        description: MQTT Topic where received msgs are
        selector:
          text:
              autocomplete: "DroidPad/Events"
              type: text

    - event_type:
        name: Witch type of trigger is
        selector:
          select:
            options:
              - label: switch
                value: switch
              - label: slider
                value: slider
              - label: joystick
                value: joystick
              - label: button
                value: button
              - label: dpad
                value: dpad

mode: restart
max_exceeded: silent

triggers:
  trigger: mqtt
  topic: !input mqtt_topic

variables:
  event_type: !input event_type

actions:
  - action: persistent_notification.create
    data:
    title: >
      DroidPad Event is {{ event_type }}
    message: "Value is {{ event_type }}"
      
      

